// Code generated by go generate; DO NOT EDIT.

package mceliece6688128f

func bm(out *[SysT + 1]gf, s *[SysT * 2]gf) {
	var N, L uint16
	var mle, mne uint16
	var T, C, B [SysT + 1]gf
	var b gf = 1
	B[1] = 1
	C[0] = 1

	for N = 0; N < 2*SysT; N++ {
		var d gf
		limit := int(N)
		if limit > SysT {
			limit = SysT
		}
		for i := 0; i <= limit; i++ {
			d ^= gfMul(C[i], s[int(N)-i])
		}

		mne = uint16(d)
		mne--
		mne >>= 15
		mne--
		mle = N
		mle -= 2 * L
		mle >>= 15
		mle--
		mle &= mne

		for i := 0; i <= SysT; i++ {
			T[i] = C[i]
		}

		f := gfFrac(b, d)
		for i := 0; i <= SysT; i++ {
			C[i] ^= gfMul(f, B[i]) & gf(mne)
		}

		L = (L & ^mle) | ((N + 1 - L) & mle)
		for i := 0; i <= SysT; i++ {
			B[i] = (B[i] & gf(^mle)) | (T[i] & gf(mle))
		}
		b = (b & gf(^mle)) | (d & gf(mle))

		for i := SysT; i >= 1; i-- {
			B[i] = B[i-1]
		}
		B[0] = 0
	}

	for i := 0; i <= SysT; i++ {
		out[i] = C[SysT-i]
	}
}
