// Code generated by go generate; DO NOT EDIT.

package mceliece6688128f

import "io"

func sameMask8(x, y uint16) byte {
	mask := uint32(x ^ y)
	mask--
	mask >>= 31
	mask = -mask
	return byte(mask & 0xff)
}

func genE(e []byte, rng io.Reader) error {
	var buf [SysT * 2 * 2]byte
	var nums [SysT * 2]uint16
	var ind [SysT]uint16
	var val [SysT]byte

	for {
		if _, err := io.ReadFull(rng, buf[:]); err != nil {
			return errNoRandom
		}
		for i := 0; i < SysT*2; i++ {
			nums[i] = uint16(loadGF(buf[i*2:]))
		}
		count := 0
		for i := 0; i < SysT*2 && count < SysT; i++ {
			if uint16SmallerMask(nums[i], SysN) == 0xffff {
				ind[count] = nums[i]
				count++
			}
		}
		if count < SysT {
			continue
		}
		eq := 0
		for i := 1; i < SysT; i++ {
			for j := 0; j < i; j++ {
				if uint32EqualMask(uint32(ind[i]), uint32(ind[j])) == ^uint32(0) {
					eq = 1
				}
			}
		}
		if eq == 0 {
			break
		}
	}

	for j := 0; j < SysT; j++ {
		val[j] = 1 << uint(ind[j]&7)
	}
	for i := 0; i < SysN/8; i++ {
		e[i] = 0
		for j := 0; j < SysT; j++ {
			mask := sameMask8(uint16(i), ind[j]>>3)
			e[i] |= val[j] & mask
		}
	}
	return nil
}

func loadPublicKeyRow(row *[SysN / 8]byte, pk []byte, pkPtr int) {
	for j := 0; j < SysN/8; j++ {
		row[j] = 0
	}
	for j := 0; j < PKRowBytes; j++ {
		row[SysN/8-PKRowBytes+j] = pk[pkPtr+j]
	}
}

func syndrome(s []byte, pk []byte, e []byte) {
	var row [SysN / 8]byte
	pkPtr := 0
	for i := 0; i < SyndBytes; i++ {
		s[i] = 0
	}
	for i := 0; i < PKNRows; i++ {
		loadPublicKeyRow(&row, pk, pkPtr)
		row[i/8] |= 1 << uint(i%8)

		var b byte
		for j := 0; j < SysN/8; j++ {
			b ^= row[j] & e[j]
		}
		b ^= b >> 4
		b ^= b >> 2
		b ^= b >> 1
		b &= 1
		s[i/8] |= b << uint(i%8)
		pkPtr += PKRowBytes
	}
}

func encrypt(s []byte, pk []byte, e []byte, rng io.Reader) error {
	if err := genE(e, rng); err != nil {
		return err
	}
	syndrome(s, pk, e)
	return nil
}
