// Code generated by go generate; DO NOT EDIT.

package mceliece6688128f

import (
	"bytes"
	"testing"
)

func TestRound4Sizes(t *testing.T) {
	if PublicKeySize != 1044992 || PrivateKeySize != 13932 || CiphertextSize != 208 || SharedKeySize != 32 {
		t.Fatalf("unexpected sizes: pk=%d sk=%d ct=%d ss=%d", PublicKeySize, PrivateKeySize, CiphertextSize, SharedKeySize)
	}
}

func TestRoundTripDeterministic(t *testing.T) {
	seed := bytes.Repeat([]byte{0x42}, SeedSize)
	pk, sk, err := GenerateKeyPairFromSeed(seed)
	if err != nil {
		t.Fatal(err)
	}
	ct, ss, err := EncapsulateFromSeed(pk, bytes.Repeat([]byte{0x24}, 32))
	if err != nil {
		t.Fatal(err)
	}
	ss2, err := Decapsulate(sk, ct)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(ss, ss2) {
		t.Fatalf("shared secret mismatch")
	}
}

func TestRecoverPublicKey(t *testing.T) {
	seed := bytes.Repeat([]byte{0x77}, SeedSize)
	pk, sk, err := GenerateKeyPairFromSeed(seed)
	if err != nil {
		t.Fatal(err)
	}
	got, err := PublicKeyFromPrivateKey(sk)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(pk, got) {
		t.Fatalf("recovered public key mismatch")
	}
}
