// Code generated by go generate; DO NOT EDIT.

package mceliece6688128f

import (
	"errors"

	"github.com/cloudflare/circl/kem/classicmceliece/internal/matops"
)

func ctz(in uint64) int {
	m := 0
	r := 0
	for i := 0; i < 64; i++ {
		b := int((in >> uint(i)) & 1)
		m |= b
		r += (m ^ 1) & (b ^ 1)
	}
	return r
}

func sameMask64(x, y uint16) uint64 {
	mask := uint64(x ^ y)
	mask--
	mask >>= 63
	mask = -mask
	return mask
}

func loadPivotWindow(mat *[PKNRows][SysN / 8]byte, row, blockIdx int) uint64 {
	return load8(mat[row][blockIdx:])
}

func storePivotWindow(mat *[PKNRows][SysN / 8]byte, row, blockIdx int, t uint64) {
	store8(mat[row][blockIdx:], t)
}

func movColumns(mat *[PKNRows][SysN / 8]byte, pi *[1 << GFBits]int16, pivots *uint64) int {
	var buf [64]uint64
	var ctzList [32]uint64
	row := PKNRows - 32
	blockIdx := row / 8

	for i := 0; i < 32; i++ {
		buf[i] = loadPivotWindow(mat, row+i, blockIdx)
	}
	*pivots = 0
	for i := 0; i < 32; i++ {
		t := buf[i]
		for j := i + 1; j < 32; j++ {
			t |= buf[j]
		}
		if uint64ZeroMask(t) == ^uint64(0) {
			return -1
		}
		s := ctz(t)
		ctzList[i] = uint64(s)
		*pivots |= uint64(1) << uint(s)
		for j := i + 1; j < 32; j++ {
			mask := (buf[i] >> uint(s)) & 1
			mask--
			buf[i] ^= buf[j] & mask
		}
		for j := i + 1; j < 32; j++ {
			mask := (buf[j] >> uint(s)) & 1
			mask = -mask
			buf[j] ^= buf[i] & mask
		}
	}

	for j := 0; j < 32; j++ {
		for k := j + 1; k < 64; k++ {
			d := uint64(uint16(pi[row+j]) ^ uint16(pi[row+k]))
			d &= sameMask64(uint16(k), uint16(ctzList[j]))
			pi[row+j] ^= int16(d)
			pi[row+k] ^= int16(d)
		}
	}

	for i := 0; i < PKNRows; i++ {
		t := loadPivotWindow(mat, i, blockIdx)
		for j := 0; j < 32; j++ {
			d := t >> uint(j)
			d ^= t >> uint(ctzList[j])
			d &= 1
			t ^= d << uint(ctzList[j])
			t ^= d << uint(j)
		}
		storePivotWindow(mat, i, blockIdx, t)
	}
	return 0
}

func storePublicKeyFromMatrix(pk []byte, mat *[PKNRows][SysN / 8]byte) {
	for i := 0; i < PKNRows; i++ {
		copy(pk[i*PKRowBytes:(i+1)*PKRowBytes], mat[i][PKNRows/8:PKNRows/8+PKRowBytes])
	}
}

func pkGen(pk []byte, sk []byte, perm *[1 << GFBits]uint32, pi *[1 << GFBits]int16, pivots *uint64) int {
	var buf [1 << GFBits]uint64
	var mat [PKNRows][SysN / 8]byte
	var g [SysT + 1]gf
	var L [SysN]gf
	var inv [SysN]gf

	g[SysT] = 1
	for i := 0; i < SysT; i++ {
		g[i] = loadGF(sk[i*2:])
	}
	for i := 0; i < (1 << GFBits); i++ {
		buf[i] = uint64(perm[i])
		buf[i] <<= 31
		buf[i] |= uint64(i)
	}
	uint64Sort(buf[:])
	for i := 1; i < (1 << GFBits); i++ {
		if uint64EqualMask(buf[i-1]>>31, buf[i]>>31) == ^uint64(0) {
			return -1
		}
	}
	for i := 0; i < (1 << GFBits); i++ {
		pi[i] = int16(buf[i] & GFMask)
	}
	for i := 0; i < SysN; i++ {
		L[i] = bitrev(gf(pi[i]))
	}

	root(&inv, &g, &L)
	for i := 0; i < SysN; i++ {
		inv[i] = gfInv(inv[i])
	}

	for i := 0; i < SysT; i++ {
		for j := 0; j < SysN; j += 8 {
			for k := 0; k < GFBits; k++ {
				b := byte((inv[j+7] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+6] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+5] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+4] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+3] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+2] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+1] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+0] >> uint(k)) & 1)
				mat[i*GFBits+k][j/8] = b
			}
		}
		for j := 0; j < SysN; j++ {
			inv[j] = gfMul(inv[j], L[j])
		}
	}

	for i := 0; i < (PKNRows+7)/8; i++ {
		for j := 0; j < 8; j++ {
			row := i*8 + j
			if row >= PKNRows {
				break
			}
			if row == PKNRows-32 {
				if movColumns(&mat, pi, pivots) != 0 {
					return -1
				}
			}
			for k := row + 1; k < PKNRows; k++ {
				mask := mat[row][i] ^ mat[k][i]
				mask >>= uint(j)
				mask &= 1
				mask = -mask
				matops.AddMasked(mat[row][:], mat[k][:], mask)
			}
			if uint64ZeroMask(uint64((mat[row][i]>>uint(j))&1)) == ^uint64(0) {
				return -1
			}
			for k := 0; k < PKNRows; k++ {
				if k != row {
					mask := mat[k][i] >> uint(j)
					mask &= 1
					mask = -mask
					matops.AddMasked(mat[k][:], mat[row][:], mask)
				}
			}
		}
	}
	storePublicKeyFromMatrix(pk, &mat)
	return 0
}

func PublicKeyFromPrivateKey(sk []byte) ([]byte, error) {
	if len(sk) != PrivateKeySize {
		return nil, errors.New("classicmceliece: wrong private key size")
	}
	pk := make([]byte, PublicKeySize)
	if pkGenFromSK(pk, sk[40:]) != 0 {
		return nil, errors.New("classicmceliece: invalid private key")
	}
	return pk, nil
}

func pkGenFromSK(pk []byte, sk []byte) int {
	var mat [PKNRows][SysN / 8]byte
	var g [SysT + 1]gf
	var L [SysN]gf
	var inv [SysN]gf

	g[SysT] = 1
	for i := 0; i < SysT; i++ {
		g[i] = loadGF(sk[i*2:])
	}
	supportGen(&L, sk[IrrBytes:])
	root(&inv, &g, &L)
	for i := 0; i < SysN; i++ {
		inv[i] = gfInv(inv[i])
	}

	for i := 0; i < SysT; i++ {
		for j := 0; j < SysN; j += 8 {
			for k := 0; k < GFBits; k++ {
				b := byte((inv[j+7] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+6] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+5] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+4] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+3] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+2] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+1] >> uint(k)) & 1)
				b <<= 1
				b |= byte((inv[j+0] >> uint(k)) & 1)
				mat[i*GFBits+k][j/8] = b
			}
		}
		for j := 0; j < SysN; j++ {
			inv[j] = gfMul(inv[j], L[j])
		}
	}

	for i := 0; i < (PKNRows+7)/8; i++ {
		for j := 0; j < 8; j++ {
			row := i*8 + j
			if row >= PKNRows {
				break
			}
			for k := row + 1; k < PKNRows; k++ {
				mask := mat[row][i] ^ mat[k][i]
				mask >>= uint(j)
				mask &= 1
				mask = -mask
				matops.AddMasked(mat[row][:], mat[k][:], mask)
			}
			if uint64ZeroMask(uint64((mat[row][i]>>uint(j))&1)) == ^uint64(0) {
				return -1
			}
			for k := 0; k < PKNRows; k++ {
				if k != row {
					mask := mat[k][i] >> uint(j)
					mask &= 1
					mask = -mask
					matops.AddMasked(mat[k][:], mat[row][:], mask)
				}
			}
		}
	}
	storePublicKeyFromMatrix(pk, &mat)
	return 0
}
