// Code generated by go generate; DO NOT EDIT.

package mceliece460896

func decrypt(e []byte, sk []byte, c []byte) int {
	var r [SysN / 8]byte
	var g [SysT + 1]gf
	var L [SysN]gf
	var s [SysT * 2]gf
	var sCmp [SysT * 2]gf
	var locator [SysT + 1]gf
	var images [SysN]gf

	for i := 0; i < SyndBytes; i++ {
		r[i] = c[i]
	}
	for i := 0; i < SysT; i++ {
		g[i] = loadGF(sk[i*2:])
	}
	g[SysT] = 1

	supportGen(&L, sk[IrrBytes:])
	synd(&s, &g, &L, r[:])
	bm(&locator, &s)
	root(&images, &locator, &L)

	for i := 0; i < SysN/8; i++ {
		e[i] = 0
	}
	w := 0
	for i := 0; i < SysN; i++ {
		t := byte(gfIsZero(images[i]) & 1)
		e[i/8] |= t << uint(i%8)
		w += int(t)
	}

	synd(&sCmp, &g, &L, e)

	check := uint16(w)
	check ^= SysT
	for i := 0; i < SysT*2; i++ {
		check |= uint16(s[i] ^ sCmp[i])
	}
	check--
	check >>= 15
	return int(check ^ 1)
}
