// Code generated by go generate; DO NOT EDIT.

// Package mceliece460896 implements the Classic McEliece mceliece460896
// Round 4 parameter set. The code is a direct, scalar Go port of the official
// 2022-10-23 reference implementation.
package mceliece460896

const (
	GFBits = 13
	SysN   = 4608
	SysT   = 96

	CondBytes = (1 << (GFBits - 4)) * (2*GFBits - 1)
	IrrBytes  = SysT * 2

	PKNRows     = SysT * GFBits
	PKNCols     = SysN - PKNRows
	PKRowBytes  = (PKNCols + 7) / 8
	SyndBytes   = (PKNRows + 7) / 8
	PKNRowsMod8 = PKNRows % 8

	GFMask = (1 << GFBits) - 1

	PublicKeySize  = 524160
	PrivateKeySize = 13608
	CiphertextSize = 156
	SharedKeySize  = 32
	SeedSize       = 32
)

type gf uint16
