// Code generated by go generate; DO NOT EDIT.

package mceliece460896

import (
	"crypto/rand"
	"encoding/binary"
	"errors"
	"io"

	"github.com/cloudflare/circl/internal/sha3"
)

func storeGF(dest []byte, a gf) {
	dest[0] = byte(a)
	dest[1] = byte(a >> 8)
}

func loadGF(src []byte) gf {
	return gf(binary.LittleEndian.Uint16(src) & GFMask)
}

func load4(in []byte) uint32       { return binary.LittleEndian.Uint32(in) }
func load8(in []byte) uint64       { return binary.LittleEndian.Uint64(in) }
func store8(out []byte, in uint64) { binary.LittleEndian.PutUint64(out, in) }

func bitrev(a gf) gf {
	x := uint16(a)
	x = ((x & 0x00FF) << 8) | ((x & 0xFF00) >> 8)
	x = ((x & 0x0F0F) << 4) | ((x & 0xF0F0) >> 4)
	x = ((x & 0x3333) << 2) | ((x & 0xCCCC) >> 2)
	x = ((x & 0x5555) << 1) | ((x & 0xAAAA) >> 1)
	return gf(x >> 3)
}

func shake256(out, in []byte) {
	h := sha3.NewShake256()
	_, _ = h.Write(in)
	_, _ = h.Read(out)
}

func cryptoHash32(out, in []byte) {
	shake256(out[:32], in)
}

type shakeReader struct{ h sha3.State }

func newShakeReader(seed []byte) *shakeReader {
	h := sha3.NewShake256()
	_, _ = h.Write(seed)
	return &shakeReader{h: h}
}

func (r *shakeReader) Read(p []byte) (int, error) { return r.h.Read(p) }

func fillRandom(out []byte) error {
	_, err := io.ReadFull(rand.Reader, out)
	return err
}

var errNoRandom = errors.New("classicmceliece: random source failed")
