// Code generated by command: go run src.go -out ../f1600x4_amd64.s -stubs ../f1600x4stubs_amd64.go -pkg f1600x4. DO NOT EDIT.

// +build amd64

package f1600x4

//go:noescape
func f1600x4(state *uint64, rc *[24]uint64)
