// Code generated by go generate; DO NOT EDIT.

package mceliece460896f

func cbrecursion(out []byte, pos, step int64, pi []int16, w, n int64, temp []int32) {
	A := temp[:n]
	B := temp[n : 2*n]

	if w == 1 {
		out[pos>>3] ^= byte(pi[0]) << uint(pos&7)
		return
	}

	for x := int64(0); x < n; x++ {
		A[x] = (int32(pi[x]^1) << 16) | int32(uint16(pi[x^1]))
	}
	int32Sort(A)

	for x := int64(0); x < n; x++ {
		Ax := A[x]
		px := Ax & 0xffff
		cx := int32Min(px, int32(x))
		B[x] = (px << 16) | cx
	}

	for x := int64(0); x < n; x++ {
		A[x] = (A[x] << 16) | int32(x)
	}
	int32Sort(A)

	for x := int64(0); x < n; x++ {
		A[x] = (A[x] << 16) + (B[x] >> 16)
	}
	int32Sort(A)

	if w <= 10 {
		for x := int64(0); x < n; x++ {
			B[x] = ((A[x] & 0xffff) << 10) | (B[x] & 0x3ff)
		}
		for i := int64(1); i < w-1; i++ {
			for x := int64(0); x < n; x++ {
				A[x] = ((B[x] &^ 0x3ff) << 6) | int32(x)
			}
			int32Sort(A)
			for x := int64(0); x < n; x++ {
				A[x] = (A[x] << 20) | B[x]
			}
			int32Sort(A)
			for x := int64(0); x < n; x++ {
				ppcpx := A[x] & 0xfffff
				ppcx := (A[x] & 0xffc00) | (B[x] & 0x3ff)
				B[x] = int32Min(ppcx, ppcpx)
			}
		}
		for x := int64(0); x < n; x++ {
			B[x] &= 0x3ff
		}
	} else {
		for x := int64(0); x < n; x++ {
			B[x] = (A[x] << 16) | (B[x] & 0xffff)
		}
		for i := int64(1); i < w-1; i++ {
			for x := int64(0); x < n; x++ {
				A[x] = (B[x] &^ 0xffff) | int32(x)
			}
			int32Sort(A)
			for x := int64(0); x < n; x++ {
				A[x] = (A[x] << 16) | (B[x] & 0xffff)
			}
			if i < w-2 {
				for x := int64(0); x < n; x++ {
					B[x] = (A[x] &^ 0xffff) | (B[x] >> 16)
				}
				int32Sort(B)
				for x := int64(0); x < n; x++ {
					B[x] = (B[x] << 16) | (A[x] & 0xffff)
				}
			}
			int32Sort(A)
			for x := int64(0); x < n; x++ {
				cpx := (B[x] &^ 0xffff) | (A[x] & 0xffff)
				B[x] = int32Min(B[x], cpx)
			}
		}
		for x := int64(0); x < n; x++ {
			B[x] &= 0xffff
		}
	}

	for x := int64(0); x < n; x++ {
		A[x] = (int32(pi[x]) << 16) + int32(x)
	}
	int32Sort(A)

	for j := int64(0); j < n/2; j++ {
		x := 2 * j
		fj := B[x] & 1
		Fx := int32(x) + fj
		Fx1 := Fx ^ 1

		out[pos>>3] ^= byte(fj) << uint(pos&7)
		pos += step

		B[x] = (A[x] << 16) | Fx
		B[x+1] = (A[x+1] << 16) | Fx1
	}
	int32Sort(B)

	pos += (2*w - 3) * step * (n / 2)

	for k := int64(0); k < n/2; k++ {
		y := 2 * k
		lk := B[y] & 1
		Ly := int32(y) + lk
		Ly1 := Ly ^ 1

		out[pos>>3] ^= byte(lk) << uint(pos&7)
		pos += step

		A[y] = (Ly << 16) | (B[y] & 0xffff)
		A[y+1] = (Ly1 << 16) | (B[y+1] & 0xffff)
	}
	int32Sort(A)

	pos -= (2*w - 2) * step * (n / 2)

	q := make([]int16, n)
	for j := int64(0); j < n/2; j++ {
		q[j] = int16((A[2*j] & 0xffff) >> 1)
		q[j+n/2] = int16((A[2*j+1] & 0xffff) >> 1)
	}

	cbrecursion(out, pos, step*2, q[:n/2], w-1, n/2, temp)
	cbrecursion(out, pos+step, step*2, q[n/2:], w-1, n/2, temp)
}

func controlBitsLayer(p []int16, cb []byte, s int) {
	n := len(p)
	stride := 1 << s
	index := 0
	for i := 0; i < n; i += stride * 2 {
		for j := 0; j < stride; j++ {
			d := p[i+j] ^ p[i+j+stride]
			m := int16((cb[index>>3] >> uint(index&7)) & 1)
			m = -m
			d &= m
			p[i+j] ^= d
			p[i+j+stride] ^= d
			index++
		}
	}
}

func controlBitsFromPermutation(out []byte, pi *[1 << GFBits]int16) {
	w := int64(GFBits)
	n := int64(1 << GFBits)
	temp := make([]int32, 2*n)
	piTest := make([]int16, n)

	for {
		for i := range out {
			out[i] = 0
		}
		cbrecursion(out, 0, 1, pi[:], w, n, temp)

		for i := int64(0); i < n; i++ {
			piTest[i] = int16(i)
		}
		ptr := 0
		for i := 0; i < GFBits; i++ {
			controlBitsLayer(piTest, out[ptr:], i)
			ptr += int(n >> 4)
		}
		for i := GFBits - 2; i >= 0; i-- {
			controlBitsLayer(piTest, out[ptr:], i)
			ptr += int(n >> 4)
		}
		var diff int16
		for i := int64(0); i < n; i++ {
			diff |= pi[i] ^ piTest[i]
		}
		if int16NonzeroMask(diff) == 0 {
			break
		}
	}
}
