// Code generated by go generate; DO NOT EDIT.

// Package mceliece460896 implements the Classic McEliece mceliece460896
// Round 4 KEM parameter set.
package mceliece460896

import (
	"bytes"
	cryptoRand "crypto/rand"
	"crypto/subtle"
	"errors"
	"io"

	"github.com/cloudflare/circl/kem"
	core "github.com/cloudflare/circl/kem/classicmceliece/internal/mceliece460896"
)

const (
	// KeySeedSize is the size of seed for NewKeyFromSeed.
	KeySeedSize = core.SeedSize

	// EncapsulationSeedSize is the size of seed for EncapsulateTo.
	EncapsulationSeedSize = 32

	// SharedKeySize is the size of the established shared key.
	SharedKeySize = core.SharedKeySize

	// CiphertextSize is the size of the encapsulated shared key.
	CiphertextSize = core.CiphertextSize

	// PublicKeySize is the size of a packed public key.
	PublicKeySize = core.PublicKeySize

	// PrivateKeySize is the size of a packed private key, matching the official
	// Round 4 CRYPTO_SECRETKEYBYTES value.
	PrivateKeySize = core.PrivateKeySize
)

// PublicKey is a mceliece460896 public key.
type PublicKey struct {
	data []byte
}

// PrivateKey is a mceliece460896 private key.
type PrivateKey struct {
	data []byte
	pk   *PublicKey
}

// NewKeyFromSeed derives a public/private keypair deterministically from seed.
// It panics if seed is not KeySeedSize bytes.
func NewKeyFromSeed(seed []byte) (*PublicKey, *PrivateKey) {
	if len(seed) != KeySeedSize {
		panic("seed must be of length KeySeedSize")
	}
	pkBytes, skBytes, err := core.GenerateKeyPairFromSeed(seed)
	if err != nil {
		panic(err)
	}
	pk := &PublicKey{data: pkBytes}
	sk := &PrivateKey{data: skBytes, pk: pk}
	return pk, sk
}

// GenerateKeyPair generates public and private keys using entropy from rand.
// If rand is nil, crypto/rand.Reader is used.
func GenerateKeyPair(rand io.Reader) (*PublicKey, *PrivateKey, error) {
	var seed [KeySeedSize]byte
	if rand == nil {
		rand = cryptoRand.Reader
	}
	if _, err := io.ReadFull(rand, seed[:]); err != nil {
		return nil, nil, err
	}
	pk, sk := NewKeyFromSeed(seed[:])
	return pk, sk, nil
}

// EncapsulateTo writes a ciphertext and shared secret for pk. If seed is nil,
// crypto/rand.Reader is used; otherwise seed must be EncapsulationSeedSize bytes.
func (pk *PublicKey) EncapsulateTo(ct, ss, seed []byte) {
	if len(ct) != CiphertextSize {
		panic("ct must be of length CiphertextSize")
	}
	if len(ss) != SharedKeySize {
		panic("ss must be of length SharedKeySize")
	}
	if seed == nil {
		seed = make([]byte, EncapsulationSeedSize)
		if _, err := cryptoRand.Read(seed); err != nil {
			panic(err)
		}
	} else if len(seed) != EncapsulationSeedSize {
		panic("seed must be of length EncapsulationSeedSize")
	}
	rawCT, rawSS, err := core.EncapsulateFromSeed(pk.data, seed)
	if err != nil {
		panic(err)
	}
	copy(ct, rawCT)
	copy(ss, rawSS)
}

// DecapsulateTo writes the shared secret encapsulated in ct for sk.
func (sk *PrivateKey) DecapsulateTo(ss, ct []byte) {
	if len(ct) != CiphertextSize {
		panic("ct must be of length CiphertextSize")
	}
	if len(ss) != SharedKeySize {
		panic("ss must be of length SharedKeySize")
	}
	rawSS, err := core.Decapsulate(sk.data, ct)
	if err != nil {
		panic(err)
	}
	copy(ss, rawSS)
}

// Pack writes pk to buf and panics unless buf is PublicKeySize bytes.
func (pk *PublicKey) Pack(buf []byte) {
	if len(buf) != PublicKeySize {
		panic("buf must be of length PublicKeySize")
	}
	copy(buf, pk.data)
}

// Unpack reads pk from buf and panics unless buf is PublicKeySize bytes.
func (pk *PublicKey) Unpack(buf []byte) {
	if len(buf) != PublicKeySize {
		panic("buf must be of length PublicKeySize")
	}
	pk.data = append(pk.data[:0], buf...)
}

// Pack writes sk to buf and panics unless buf is PrivateKeySize bytes.
func (sk *PrivateKey) Pack(buf []byte) {
	if len(buf) != PrivateKeySize {
		panic("buf must be of length PrivateKeySize")
	}
	copy(buf, sk.data)
}

// Unpack reads sk from buf, reconstructs the public key, and panics unless buf
// is PrivateKeySize bytes and represents a key whose public key can be derived.
func (sk *PrivateKey) Unpack(buf []byte) {
	if len(buf) != PrivateKeySize {
		panic("buf must be of length PrivateKeySize")
	}
	data := append(sk.data[:0], buf...)
	pkBytes, err := core.PublicKeyFromPrivateKey(data)
	if err != nil {
		panic(err)
	}
	sk.data = data
	sk.pk = &PublicKey{data: pkBytes}
}

func (*scheme) Name() string               { return "Classic-McEliece-460896" }
func (*scheme) PublicKeySize() int         { return PublicKeySize }
func (*scheme) PrivateKeySize() int        { return PrivateKeySize }
func (*scheme) SeedSize() int              { return KeySeedSize }
func (*scheme) SharedKeySize() int         { return SharedKeySize }
func (*scheme) CiphertextSize() int        { return CiphertextSize }
func (*scheme) EncapsulationSeedSize() int { return EncapsulationSeedSize }

func (sk *PrivateKey) Scheme() kem.Scheme { return sch }
func (pk *PublicKey) Scheme() kem.Scheme  { return sch }

func (sk *PrivateKey) MarshalBinary() ([]byte, error) {
	ret := make([]byte, PrivateKeySize)
	sk.Pack(ret)
	return ret, nil
}

func (pk *PublicKey) MarshalBinary() ([]byte, error) {
	ret := make([]byte, PublicKeySize)
	pk.Pack(ret)
	return ret, nil
}

func (sk *PrivateKey) Equal(other kem.PrivateKey) bool {
	oth, ok := other.(*PrivateKey)
	if !ok {
		return false
	}
	if subtle.ConstantTimeCompare(sk.data, oth.data) != 1 {
		return false
	}
	if sk.pk == nil || oth.pk == nil {
		return sk.pk == nil && oth.pk == nil
	}
	return sk.pk.Equal(oth.pk)
}

func (pk *PublicKey) Equal(other kem.PublicKey) bool {
	oth, ok := other.(*PublicKey)
	if !ok {
		return false
	}
	return bytes.Equal(pk.data, oth.data)
}

func (sk *PrivateKey) Public() kem.PublicKey {
	if sk.pk == nil {
		return nil
	}
	return &PublicKey{data: append([]byte(nil), sk.pk.data...)}
}

type scheme struct{}

var sch kem.Scheme = &scheme{}

// Scheme returns a KEM interface for mceliece460896.
func Scheme() kem.Scheme { return sch }

func (*scheme) GenerateKeyPair() (kem.PublicKey, kem.PrivateKey, error) {
	return GenerateKeyPair(cryptoRand.Reader)
}

func (*scheme) DeriveKeyPair(seed []byte) (kem.PublicKey, kem.PrivateKey) {
	if len(seed) != KeySeedSize {
		panic(kem.ErrSeedSize)
	}
	return NewKeyFromSeed(seed)
}

func (*scheme) Encapsulate(pk kem.PublicKey) (ct, ss []byte, err error) {
	pub, ok := pk.(*PublicKey)
	if !ok {
		return nil, nil, kem.ErrTypeMismatch
	}
	ct = make([]byte, CiphertextSize)
	ss = make([]byte, SharedKeySize)
	pub.EncapsulateTo(ct, ss, nil)
	return ct, ss, nil
}

func (*scheme) EncapsulateDeterministically(pk kem.PublicKey, seed []byte) (ct, ss []byte, err error) {
	if len(seed) != EncapsulationSeedSize {
		return nil, nil, kem.ErrSeedSize
	}
	pub, ok := pk.(*PublicKey)
	if !ok {
		return nil, nil, kem.ErrTypeMismatch
	}
	ct = make([]byte, CiphertextSize)
	ss = make([]byte, SharedKeySize)
	pub.EncapsulateTo(ct, ss, seed)
	return ct, ss, nil
}

func (*scheme) Decapsulate(sk kem.PrivateKey, ct []byte) ([]byte, error) {
	if len(ct) != CiphertextSize {
		return nil, kem.ErrCiphertextSize
	}
	priv, ok := sk.(*PrivateKey)
	if !ok {
		return nil, kem.ErrTypeMismatch
	}
	ss := make([]byte, SharedKeySize)
	priv.DecapsulateTo(ss, ct)
	return ss, nil
}

func (*scheme) UnmarshalBinaryPublicKey(buf []byte) (kem.PublicKey, error) {
	if len(buf) != PublicKeySize {
		return nil, kem.ErrPubKeySize
	}
	ret := &PublicKey{data: append([]byte(nil), buf...)}
	return ret, nil
}

func (*scheme) UnmarshalBinaryPrivateKey(buf []byte) (kem.PrivateKey, error) {
	if len(buf) != PrivateKeySize {
		return nil, kem.ErrPrivKeySize
	}
	data := append([]byte(nil), buf...)
	pkBytes, err := core.PublicKeyFromPrivateKey(data)
	if err != nil {
		return nil, errors.Join(kem.ErrPrivKey, err)
	}
	return &PrivateKey{data: data, pk: &PublicKey{data: pkBytes}}, nil
}
