// Code generated by go generate; DO NOT EDIT.

package mceliece6960119f

import (
	"errors"
	"io"
)

func GenerateKeyPair() (pk, sk []byte, err error) {
	return GenerateKeyPairWithRandom(cryptoRandReader{})
}

func GenerateKeyPairWithRandom(rng io.Reader) (pk, sk []byte, err error) {
	if rng == nil {
		rng = cryptoRandReader{}
	}
	seed := make([]byte, SeedSize)
	if _, err := io.ReadFull(rng, seed); err != nil {
		return nil, nil, err
	}
	return GenerateKeyPairFromSeed(seed)
}

func GenerateKeyPairFromSeed(seed []byte) (pk, sk []byte, err error) {
	if len(seed) != SeedSize {
		return nil, nil, errors.New("classicmceliece: wrong seed size")
	}
	pk = make([]byte, PublicKeySize)
	sk = make([]byte, PrivateKeySize)

	var seedBuf [33]byte
	seedBuf[0] = 64
	copy(seedBuf[1:], seed)

	var r [SysN/8 + (1<<GFBits)*4 + SysT*2 + 32]byte
	var f [SysT]gf
	var irr [SysT]gf
	var perm [1 << GFBits]uint32
	var pi [1 << GFBits]int16
	var pivots uint64
	pivots = 0xFFFFFFFF

	for {
		shake256(r[:], seedBuf[:])
		copy(sk[:32], seedBuf[1:])
		copy(seedBuf[1:], r[len(r)-32:])

		skp := 32 + 8
		rp := len(r) - 32

		rp -= SysT * 2
		for i := 0; i < SysT; i++ {
			f[i] = loadGF(r[rp+i*2:])
		}
		if genpolyGen(&irr, &f) != 0 {
			continue
		}
		for i := 0; i < SysT; i++ {
			storeGF(sk[skp+i*2:], irr[i])
		}
		skp += IrrBytes

		rp -= (1 << GFBits) * 4
		for i := 0; i < (1 << GFBits); i++ {
			perm[i] = load4(r[rp+i*4:])
		}
		if pkGen(pk, sk[32+8:32+8+IrrBytes], &perm, &pi, &pivots) != 0 {
			continue
		}

		controlBitsFromPermutation(sk[skp:skp+CondBytes], &pi)
		skp += CondBytes

		rp -= SysN / 8
		copy(sk[skp:skp+SysN/8], r[rp:rp+SysN/8])
		store8(sk[32:], pivots)
		return pk, sk, nil
	}
}

func checkPublicKeyPadding(pk []byte) int {
	var b byte
	for i := 0; i < PKNRows; i++ {
		b |= pk[i*PKRowBytes+PKRowBytes-1]
	}
	b >>= uint(PKNCols % 8)
	b--
	b >>= 7
	return int(b) - 1
}

func checkCiphertextPadding(ct []byte) int {
	b := ct[SyndBytes-1] >> uint(PKNRows%8)
	b--
	b >>= 7
	return int(b) - 1
}

func Encapsulate(pk []byte) (ct, ss []byte, err error) {
	return EncapsulateWithRandom(pk, nil)
}

func EncapsulateWithRandom(pk []byte, rng io.Reader) (ct, ss []byte, err error) {
	return encapsulateWithRandom(pk, rng)
}

func EncapsulateFromSeed(pk []byte, seed []byte) (ct, ss []byte, err error) {
	if len(seed) == 0 {
		return nil, nil, errors.New("classicmceliece: empty encapsulation seed")
	}
	return encapsulateWithRandom(pk, newShakeReader(seed))
}

func encapsulateWithRandom(pk []byte, rng io.Reader) (ct, ss []byte, err error) {
	if len(pk) != PublicKeySize {
		return nil, nil, errors.New("classicmceliece: wrong public key size")
	}
	if checkPublicKeyPadding(pk) != 0 {
		return nil, nil, errors.New("classicmceliece: invalid public key padding")
	}
	if rng == nil {
		rng = cryptoRandReader{}
	}
	ct = make([]byte, CiphertextSize)
	ss = make([]byte, SharedKeySize)
	e := make([]byte, SysN/8)
	if err := encrypt(ct, pk, e, rng); err != nil {
		return nil, nil, err
	}
	preimage := make([]byte, 1+SysN/8+SyndBytes)
	preimage[0] = 1
	copy(preimage[1:], e)
	copy(preimage[1+SysN/8:], ct)
	cryptoHash32(ss, preimage)
	return ct, ss, nil
}

type cryptoRandReader struct{}

func (cryptoRandReader) Read(p []byte) (int, error) {
	if err := fillRandom(p); err != nil {
		return 0, err
	}
	return len(p), nil
}

func Decapsulate(sk []byte, ct []byte) (ss []byte, err error) {
	if len(sk) != PrivateKeySize {
		return nil, errors.New("classicmceliece: wrong private key size")
	}
	if len(ct) != CiphertextSize {
		return nil, errors.New("classicmceliece: wrong ciphertext size")
	}
	e := make([]byte, SysN/8)
	retDecrypt := byte(decrypt(e, sk[40:], ct))
	m := uint16(retDecrypt)
	m--
	m >>= 8
	mb := byte(m)

	preimage := make([]byte, 1+SysN/8+SyndBytes)
	preimage[0] = mb & 1
	s := sk[40+IrrBytes+CondBytes:]
	for i := 0; i < SysN/8; i++ {
		preimage[1+i] = (^mb & s[i]) | (mb & e[i])
	}
	copy(preimage[1+SysN/8:], ct)
	ss = make([]byte, SharedKeySize)
	cryptoHash32(ss, preimage)
	// Constant-time implicit rejection of ciphertext padding, matching the
	// reference implementation (operations.c): the shared secret is always
	// computed and, if the ciphertext padding bits are non-zero,
	// deterministically mangled (set to all ones) rather than returned as-is.
	// checkCiphertextPadding yields 0 on valid padding and -1 (0xff) otherwise,
	// and operates only on the public ciphertext, so this stays constant time.
	// Crucially it never returns an error for a correctly sized ciphertext, so
	// a remote peer cannot force a panic through the DecapsulateTo wrapper.
	paddingMask := byte(checkCiphertextPadding(ct))
	for i := range ss {
		ss[i] |= paddingMask
	}
	return ss, nil
}
