// Code generated by go generate; DO NOT EDIT.

package mceliece6960119f

func uint16SmallerMask(x, y uint16) uint16 {
	xy := x ^ y
	z := x - y
	z ^= xy & (z ^ x ^ (1 << 15))
	return uint16(int16(z) >> 15)
}

func uint16EqualMask(x, y uint16) uint16 {
	xy := x ^ y
	return ^(uint16(int16(xy)>>15) | uint16(int16(-xy)>>15))
}

func uint32EqualMask(x, y uint32) uint32 {
	xy := x ^ y
	return ^(uint32(int32(xy)>>31) | uint32(int32(-xy)>>31))
}

func uint64EqualMask(x, y uint64) uint64 {
	xy := x ^ y
	return ^(uint64(int64(xy)>>63) | uint64(int64(-xy)>>63))
}

func uint64ZeroMask(x uint64) uint64 {
	return ^(uint64(int64(x)>>63) | uint64(int64(-x)>>63))
}

func int16NonzeroMask(x int16) int16 { return (x >> 15) | (-x >> 15) }
func int16ZeroMask(x int16) int16    { return ^int16NonzeroMask(x) }

func int32Min(x, y int32) int32 {
	xy := y ^ x
	z := y - x
	z ^= xy & (z ^ y)
	z >>= 31
	z &= xy
	return x ^ z
}
