// Code generated by go generate; DO NOT EDIT.

// Package mceliece6960119f implements the Classic McEliece mceliece6960119f
// Round 4 parameter set. The code is a direct, scalar Go port of the official
// 2022-10-23 reference implementation.
package mceliece6960119f

const (
	GFBits = 13
	SysN   = 6960
	SysT   = 119

	CondBytes = (1 << (GFBits - 4)) * (2*GFBits - 1)
	IrrBytes  = SysT * 2

	PKNRows     = SysT * GFBits
	PKNCols     = SysN - PKNRows
	PKRowBytes  = (PKNCols + 7) / 8
	SyndBytes   = (PKNRows + 7) / 8
	PKNRowsMod8 = PKNRows % 8

	GFMask = (1 << GFBits) - 1

	PublicKeySize  = 1047319
	PrivateKeySize = 13948
	CiphertextSize = 194
	SharedKeySize  = 32
	SeedSize       = 32
)

type gf uint16
