// Code generated by go generate; DO NOT EDIT.

package mceliece8192128f

func gfIsZero(a gf) gf {
	t := uint32(a)
	t--
	t >>= 19
	return gf(t)
}

func gfAdd(a, b gf) gf { return a ^ b }

func gfMul(in0, in1 gf) gf {
	t0 := uint64(in0)
	t1 := uint64(in1)
	tmp := t0 * (t1 & 1)
	for i := 1; i < GFBits; i++ {
		tmp ^= t0 * (t1 & (1 << i))
	}
	t := tmp & 0x1FF0000
	tmp ^= (t >> 9) ^ (t >> 10) ^ (t >> 12) ^ (t >> 13)
	t = tmp & 0x000E000
	tmp ^= (t >> 9) ^ (t >> 10) ^ (t >> 12) ^ (t >> 13)
	return gf(tmp & GFMask)
}

// gfSq2 returns (in^2)^2.
func gfSq2(in gf) gf {
	B := [4]uint64{0x1111111111111111, 0x0303030303030303, 0x000F000F000F000F, 0x000000FF000000FF}
	M := [4]uint64{0x0001FF0000000000, 0x000000FF80000000, 0x000000007FC00000, 0x00000000003FE000}
	x := uint64(in)
	x = (x | (x << 24)) & B[3]
	x = (x | (x << 12)) & B[2]
	x = (x | (x << 6)) & B[1]
	x = (x | (x << 3)) & B[0]
	for i := 0; i < 4; i++ {
		t := x & M[i]
		x ^= (t >> 9) ^ (t >> 10) ^ (t >> 12) ^ (t >> 13)
	}
	return gf(x & GFMask)
}

// gfSqmul returns (in^2)*m.
func gfSqmul(in, m gf) gf {
	M := [3]uint64{0x0000001FF0000000, 0x000000000FF80000, 0x000000000007E000}
	t0 := uint64(in)
	t1 := uint64(m)
	x := (t1 << 6) * (t0 & (1 << 6))
	t0 ^= t0 << 7
	x ^= t1 * (t0 & 0x04001)
	x ^= (t1 * (t0 & 0x08002)) << 1
	x ^= (t1 * (t0 & 0x10004)) << 2
	x ^= (t1 * (t0 & 0x20008)) << 3
	x ^= (t1 * (t0 & 0x40010)) << 4
	x ^= (t1 * (t0 & 0x80020)) << 5
	for i := 0; i < 3; i++ {
		t := x & M[i]
		x ^= (t >> 9) ^ (t >> 10) ^ (t >> 12) ^ (t >> 13)
	}
	return gf(x & GFMask)
}

// gfSq2mul returns ((in^2)^2)*m.
func gfSq2mul(in, m gf) gf {
	M := [6]uint64{0x1FF0000000000000, 0x000FF80000000000, 0x000007FC00000000, 0x00000003FE000000, 0x0000000001FE0000, 0x000000000001E000}
	t0 := uint64(in)
	t1 := uint64(m)
	x := (t1 << 18) * (t0 & (1 << 6))
	t0 ^= t0 << 21
	x ^= t1 * (t0 & 0x010000001)
	x ^= (t1 * (t0 & 0x020000002)) << 3
	x ^= (t1 * (t0 & 0x040000004)) << 6
	x ^= (t1 * (t0 & 0x080000008)) << 9
	x ^= (t1 * (t0 & 0x100000010)) << 12
	x ^= (t1 * (t0 & 0x200000020)) << 15
	for i := 0; i < 6; i++ {
		t := x & M[i]
		x ^= (t >> 9) ^ (t >> 10) ^ (t >> 12) ^ (t >> 13)
	}
	return gf(x & GFMask)
}

func gfFrac(den, num gf) gf {
	tmp11 := gfSqmul(den, den)
	tmp1111 := gfSq2mul(tmp11, tmp11)
	out := gfSq2(tmp1111)
	out = gfSq2mul(out, tmp1111)
	out = gfSq2(out)
	out = gfSq2mul(out, tmp1111)
	return gfSqmul(out, num)
}

func gfInv(in gf) gf { return gfFrac(in, 1) }

func gfMulPoly(out *[SysT]gf, in0, in1 *[SysT]gf) {
	var prod [SysT*2 - 1]gf
	for i := 0; i < SysT; i++ {
		for j := 0; j < SysT; j++ {
			prod[i+j] ^= gfMul(in0[i], in1[j])
		}
	}
	for i := (SysT - 1) * 2; i >= SysT; i-- {
		prod[i-SysT+7] ^= prod[i]
		prod[i-SysT+2] ^= prod[i]
		prod[i-SysT+1] ^= prod[i]
		prod[i-SysT+0] ^= prod[i]
	}
	for i := 0; i < SysT; i++ {
		out[i] = prod[i]
	}
}
