// Code generated by go generate; DO NOT EDIT.

package mceliece8192128f

import (
	"bytes"
	"crypto/aes"
	"crypto/sha256"
	"encoding/hex"
	"testing"
)

type katDRBG struct {
	key [32]byte
	v   [16]byte
}

func (d *katDRBG) init(entropy []byte) {
	if len(entropy) != 48 {
		panic("katDRBG entropy must be 48 bytes")
	}
	for i := range d.key {
		d.key[i] = 0
	}
	for i := range d.v {
		d.v[i] = 0
	}
	d.update(entropy)
}

func (d *katDRBG) Read(out []byte) (int, error) {
	block, err := aes.NewCipher(d.key[:])
	if err != nil {
		return 0, err
	}
	var buf [16]byte
	n := len(out)
	pos := 0
	for pos < len(out) {
		inc128(d.v[:])
		block.Encrypt(buf[:], d.v[:])
		pos += copy(out[pos:], buf[:])
	}
	d.update(nil)
	return n, nil
}

func (d *katDRBG) update(provided []byte) {
	block, err := aes.NewCipher(d.key[:])
	if err != nil {
		panic(err)
	}
	var temp [48]byte
	for i := 0; i < 3; i++ {
		inc128(d.v[:])
		block.Encrypt(temp[i*16:(i+1)*16], d.v[:])
	}
	if provided != nil {
		if len(provided) != 48 {
			panic("katDRBG update input must be 48 bytes")
		}
		for i := range temp {
			temp[i] ^= provided[i]
		}
	}
	copy(d.key[:], temp[:32])
	copy(d.v[:], temp[32:])
}

func inc128(v []byte) {
	for i := 15; i >= 0; i-- {
		v[i]++
		if v[i] != 0 {
			break
		}
	}
}

func TestNISTKAT(t *testing.T) {
	// These hashes were generated from the official Round 4 KAT generator in
	// Reference_Implementation/kem/mceliece8192128f/nist/kat_kem.c. The generator
	// emits full pk/sk/ct/ss vectors; this test stores SHA-256(pk || sk || ct || ss)
	// to avoid embedding multi-megabyte public keys in the source tree.
	expected := []string{
		"644ab68f9adf604e646af81cffce9ed7c1acfb85be6b67ed2393bc28a6d6ebcc",
	}

	entropy := make([]byte, 48)
	for i := range entropy {
		entropy[i] = byte(i)
	}
	var drbg katDRBG
	drbg.init(entropy)

	for count, want := range expected {
		seed := make([]byte, 48)
		drbg.Read(seed)
		var drbg2 katDRBG
		drbg2.init(seed)

		pk, sk, err := GenerateKeyPairWithRandom(&drbg2)
		if err != nil {
			t.Fatalf("count %d keypair: %v", count, err)
		}
		ct, ss, err := EncapsulateWithRandom(pk, &drbg2)
		if err != nil {
			t.Fatalf("count %d encapsulate: %v", count, err)
		}
		ss2, err := Decapsulate(sk, ct)
		if err != nil {
			t.Fatalf("count %d decapsulate: %v", count, err)
		}
		if !bytes.Equal(ss, ss2) {
			t.Fatalf("count %d shared secret mismatch", count)
		}
		h := sha256.New()
		h.Write(pk)
		h.Write(sk)
		h.Write(ct)
		h.Write(ss)
		if got := hex.EncodeToString(h.Sum(nil)); got != want {
			t.Fatalf("count %d digest mismatch:\n got %s\nwant %s", count, got, want)
		}
	}
}
