// Code generated by command: go run src.go -out ../../amd64.s -stubs ../../stubs_amd64.go -pkg matops. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func addMaskedAVX512(dst *byte, src *byte, n int, mask byte)
// Requires: AVX, AVX512BW, AVX512F
TEXT ·addMaskedAVX512(SB), NOSPLIT, $0-25
	MOVQ         dst+0(FP), AX
	MOVQ         src+8(FP), CX
	MOVQ         n+16(FP), DX
	MOVB         mask+24(FP), BL
	MOVBLZX      BL, BX
	VPBROADCASTB BX, Z0

loop:
	CMPQ     DX, $0x00
	JE       done
	VMOVDQU8 (CX), Z1
	VPANDQ   Z0, Z1, Z1
	VMOVDQU8 (AX), Z2
	VPXORQ   Z1, Z2, Z2
	VMOVDQU8 Z2, (AX)
	ADDQ     $0x40, CX
	ADDQ     $0x40, AX
	SUBQ     $0x40, DX
	JMP      loop

done:
	VZEROUPPER
	RET

// func addMaskedAVX2(dst *byte, src *byte, n int, mask byte)
// Requires: AVX, AVX2
TEXT ·addMaskedAVX2(SB), NOSPLIT, $0-25
	MOVQ         dst+0(FP), AX
	MOVQ         src+8(FP), CX
	MOVQ         n+16(FP), DX
	MOVB         mask+24(FP), BL
	MOVBLZX      BL, BX
	VMOVD        BX, X0
	VPBROADCASTB X0, Y0

loop:
	CMPQ    DX, $0x00
	JE      done
	VMOVDQU (CX), Y1
	VPAND   Y0, Y1, Y1
	VMOVDQU (AX), Y2
	VPXOR   Y1, Y2, Y2
	VMOVDQU Y2, (AX)
	ADDQ    $0x20, CX
	ADDQ    $0x20, AX
	SUBQ    $0x20, DX
	JMP     loop

done:
	VZEROUPPER
	RET
