// Code generated by command: go run src.go -out ../../amd64.s -stubs ../../stubs_amd64.go -pkg matops. DO NOT EDIT.

//go:build amd64 && !purego

package matops

// addMaskedAVX512 sets dst[i] ^= src[i] & mask for i in [0,n), with n a multiple of 64, using AVX-512. The work performed is independent of mask and of the buffer contents.
func addMaskedAVX512(dst *byte, src *byte, n int, mask byte)

// addMaskedAVX2 sets dst[i] ^= src[i] & mask for i in [0,n), with n a multiple of 32, using AVX2. The work performed is independent of mask and of the buffer contents.
func addMaskedAVX2(dst *byte, src *byte, n int, mask byte)
