// Code generated by go generate; DO NOT EDIT.

package mceliece348864f

func benesLayer(data *[64]uint64, bits *[64]uint64, lgs int) {
	s := 1 << lgs
	idx := 0
	for i := 0; i < 64; i += s * 2 {
		for j := i; j < i+s; j++ {
			d := (data[j] ^ data[j+s]) & bits[idx]
			data[j] ^= d
			data[j+s] ^= d
			idx++
		}
	}
}

func applyBenes(r []byte, bits []byte, rev bool) {
	var bs, cond [64]uint64
	for i := 0; i < 64; i++ {
		bs[i] = load8(r[i*8:])
	}

	inc := 256
	condPtr := 0
	if rev {
		inc = -256
		condPtr = (2*GFBits - 2) * 256
	}

	transpose64x64(&bs, &bs)
	for low := 0; low <= 5; low++ {
		for i := 0; i < 64; i++ {
			cond[i] = uint64(load4(bits[condPtr+i*4:]))
		}
		transpose64x64(&cond, &cond)
		benesLayer(&bs, &cond, low)
		condPtr += inc
	}

	transpose64x64(&bs, &bs)
	for low := 0; low <= 5; low++ {
		for i := 0; i < 32; i++ {
			cond[i] = load8(bits[condPtr+i*8:])
		}
		benesLayer(&bs, &cond, low)
		condPtr += inc
	}
	for low := 4; low >= 0; low-- {
		for i := 0; i < 32; i++ {
			cond[i] = load8(bits[condPtr+i*8:])
		}
		benesLayer(&bs, &cond, low)
		condPtr += inc
	}

	transpose64x64(&bs, &bs)
	for low := 5; low >= 0; low-- {
		for i := 0; i < 64; i++ {
			cond[i] = uint64(load4(bits[condPtr+i*4:]))
		}
		transpose64x64(&cond, &cond)
		benesLayer(&bs, &cond, low)
		condPtr += inc
	}
	transpose64x64(&bs, &bs)

	for i := 0; i < 64; i++ {
		store8(r[i*8:], bs[i])
	}
}

func supportGen(s *[SysN]gf, c []byte) {
	var L [GFBits][(1 << GFBits) / 8]byte
	for i := 0; i < (1 << GFBits); i++ {
		a := bitrev(gf(i))
		for j := 0; j < GFBits; j++ {
			L[j][i/8] |= byte((uint16(a)>>uint(j))&1) << uint(i%8)
		}
	}
	for j := 0; j < GFBits; j++ {
		applyBenes(L[j][:], c, false)
	}
	for i := 0; i < SysN; i++ {
		s[i] = 0
		for j := GFBits - 1; j >= 0; j-- {
			s[i] <<= 1
			s[i] |= gf((L[j][i/8] >> uint(i%8)) & 1)
		}
	}
}
