// Code generated by go generate; DO NOT EDIT.

package mceliece348864f

func gfIsZero(a gf) gf {
	t := uint32(a)
	t--
	t >>= 19
	return gf(t)
}

func gfAdd(a, b gf) gf { return a ^ b }

func gfMul(in0, in1 gf) gf {
	t0 := uint32(in0)
	t1 := uint32(in1)
	tmp := t0 * (t1 & 1)
	for i := 1; i < GFBits; i++ {
		tmp ^= t0 * (t1 & (1 << i))
	}
	t := tmp & 0x7FC000
	tmp ^= t >> 9
	tmp ^= t >> 12
	t = tmp & 0x3000
	tmp ^= t >> 9
	tmp ^= t >> 12
	return gf(tmp & GFMask)
}

func gfSq(in gf) gf {
	const (
		b0 uint32 = 0x55555555
		b1 uint32 = 0x33333333
		b2 uint32 = 0x0F0F0F0F
		b3 uint32 = 0x00FF00FF
	)
	x := uint32(in)
	x = (x | (x << 8)) & b3
	x = (x | (x << 4)) & b2
	x = (x | (x << 2)) & b1
	x = (x | (x << 1)) & b0
	t := x & 0x7FC000
	x ^= t >> 9
	x ^= t >> 12
	t = x & 0x3000
	x ^= t >> 9
	x ^= t >> 12
	return gf(x & GFMask)
}

func gfInv(in gf) gf {
	out := gfSq(in)
	tmp11 := gfMul(out, in)

	out = gfSq(tmp11)
	out = gfSq(out)
	tmp1111 := gfMul(out, tmp11)

	out = gfSq(tmp1111)
	out = gfSq(out)
	out = gfSq(out)
	out = gfSq(out)
	out = gfMul(out, tmp1111)

	out = gfSq(out)
	out = gfSq(out)
	out = gfMul(out, tmp11)

	out = gfSq(out)
	out = gfMul(out, in)

	return gfSq(out)
}

func gfFrac(den, num gf) gf { return gfMul(gfInv(den), num) }

func gfMulPoly(out *[SysT]gf, in0, in1 *[SysT]gf) {
	var prod [SysT*2 - 1]gf
	for i := 0; i < SysT; i++ {
		for j := 0; j < SysT; j++ {
			prod[i+j] ^= gfMul(in0[i], in1[j])
		}
	}
	for i := (SysT - 1) * 2; i >= SysT; i-- {
		prod[i-SysT+3] ^= prod[i]
		prod[i-SysT+1] ^= prod[i]
		prod[i-SysT+0] ^= gfMul(prod[i], 2)
	}
	for i := 0; i < SysT; i++ {
		out[i] = prod[i]
	}
}
