// Code generated by go generate; DO NOT EDIT.

// Package mceliece348864f implements the Classic McEliece mceliece348864f
// Round 4 parameter set. The code is a direct, scalar Go port of the official
// 2022-10-23 reference implementation.
package mceliece348864f

const (
	GFBits = 12
	SysN   = 3488
	SysT   = 64

	CondBytes = (1 << (GFBits - 4)) * (2*GFBits - 1)
	IrrBytes  = SysT * 2

	PKNRows     = SysT * GFBits
	PKNCols     = SysN - PKNRows
	PKRowBytes  = (PKNCols + 7) / 8
	SyndBytes   = (PKNRows + 7) / 8
	PKNRowsMod8 = PKNRows % 8

	GFMask = (1 << GFBits) - 1

	PublicKeySize  = 261120
	PrivateKeySize = 6492
	CiphertextSize = 96
	SharedKeySize  = 32
	SeedSize       = 32
)

type gf uint16
