// +build amd64

// Code autogenerated by go generate; DO NOT EDIT.

package field

import (
	"crypto/rand"
	"math/big"
	"testing"
)

type test255 struct {
	F     Arith255
	in    [2]Element255
	out   Element255
	want  big.Int
	prime big.Int
}

func csel255(io *test255) {
	b := uint(io.in[0][0]) % 2
	// big.Int
	io.want.Set(io.in[b].BigInt())
	// fp255
	io.F.CSel(&io.in[0], &io.in[1], b)
	copy(io.out[:], io.in[0][:])
}

func cswap255(io *test255) {
	var x, y big.Int
	b := uint(io.in[0][0]) % 2
	// big.Int
	if b == 0 {
		x.Set(io.in[0].BigInt())
		y.Set(io.in[1].BigInt())
	} else {
		x.Set(io.in[1].BigInt())
		y.Set(io.in[0].BigInt())
	}
	io.want.ModInverse(&y, &io.prime)
	io.want.Mul(&io.want, &x)
	io.want.Mod(&io.want, &io.prime)

	// fp255
	io.F.CSwap(&io.in[0], &io.in[1], b)
	io.F.Div(&io.out, &io.in[0], &io.in[1])
	io.F.Modp(&io.out)
}

func prime255(io *test255) {
	io.want.Set(&io.prime)
	io.out = io.F.Prime()
}

func add255(io *test255) {
	// big.Int
	io.want.Add(io.in[0].BigInt(), io.in[1].BigInt())
	io.want.Mod(&io.want, &io.prime)
	// fp255
	io.F.Add(&io.out, &io.in[0], &io.in[1])
	io.F.Modp(&io.out)
}

func subt255(io *test255) {
	// big.Int
	io.want.Sub(io.in[0].BigInt(), io.in[1].BigInt())
	io.want.Mod(&io.want, &io.prime)
	// fp255
	io.F.Sub(&io.out, &io.in[0], &io.in[1])
	io.F.Modp(&io.out)
}

func addsub255(io *test255) {
	var x, y, add, sub big.Int
	// big.Int
	x.Set(io.in[0].BigInt())
	y.Set(io.in[1].BigInt())
	add.Add(&x, &y)
	add.Mod(&add, &io.prime)
	sub.Sub(&x, &y)
	sub.Mod(&sub, &io.prime)
	io.want.Mul(&add, &sub)
	io.want.Mod(&io.want, &io.prime)
	// fp255
	io.F.AddSub(&io.in[0], &io.in[1])
	io.F.Mul(&io.out, &io.in[0], &io.in[1])
	io.F.Modp(&io.out)
}

func mul255(io *test255) {
	// big.Int
	io.want.Mul(io.in[0].BigInt(), io.in[1].BigInt())
	io.want.Mod(&io.want, &io.prime)
	// fp255
	io.F.Mul(&io.out, &io.in[0], &io.in[1])
	io.F.Modp(&io.out)
}

func sqr255(io *test255) {
	// big.Int
	x := io.in[0].BigInt()
	io.want.Mul(x, x)
	io.want.Mod(&io.want, &io.prime)
	// fp255
	io.F.Sqr(&io.out, &io.in[0])
	io.F.Modp(&io.out)
}

func modp255(io *test255) {
	// big.Int
	io.want.Mod(io.in[0].BigInt(), &io.prime)
	// fp255
	io.F.Modp(&io.in[0])
	io.out = io.in[0]
}

func divd255(io *test255) {
	// big.Int
	io.want.ModInverse(io.in[1].BigInt(), &io.prime)
	io.want.Mul(&io.want, io.in[0].BigInt())
	io.want.Mod(&io.want, &io.prime)
	// fp255
	io.F.Div(&io.out, &io.in[0], &io.in[1])
	io.F.Modp(&io.out)
}

func mulw255(io *test255) {
	// big.Int
	const A24 = 121666
	io.want.SetUint64(A24)
	io.want.Mul(&io.want, io.in[0].BigInt())
	io.want.Mod(&io.want, &io.prime)
	// fp255
	io.F.MulA24(&io.out, &io.in[0])
	io.F.Modp(&io.out)
}

func genericTest255(t *testing.T, io *test255, f func(io *test255)) {
	const numTests = 1 << 13
	for testID := 0; testID < numTests; testID++ {
		for i := range io.in {
			rand.Read(io.in[i][:])
		}
		f(io)
		got := io.out.BigInt()
		if got.Cmp(&io.want) != 0 {
			t.Errorf("[Error in %v]\nin0:%v\nin1:%v\ngot:  %v\nwant: %v",
				t.Name(),
				io.in[0].String(),
				io.in[1].String(),
				got.Text(16),
				io.want.Text(16))
		}
	}
}

func TestFp255(t *testing.T) {
	var io test255
	io.F = Fp255
	io.prime.SetUint64(1)
	io.prime.Lsh(&io.prime, 255)
	io.prime.Sub(&io.prime, new(big.Int).SetInt64(19))

	t.Run("prime", func(t *testing.T) { genericTest255(t, &io, prime255) })
	t.Run("csel", func(t *testing.T) { genericTest255(t, &io, csel255) })
	t.Run("cswap", func(t *testing.T) { genericTest255(t, &io, cswap255) })
	t.Run("add", func(t *testing.T) { genericTest255(t, &io, add255) })
	t.Run("sub", func(t *testing.T) { genericTest255(t, &io, subt255) })
	t.Run("addsub", func(t *testing.T) { genericTest255(t, &io, addsub255) })
	t.Run("mul", func(t *testing.T) { genericTest255(t, &io, mul255) })
	t.Run("sqr", func(t *testing.T) { genericTest255(t, &io, sqr255) })
	t.Run("modp", func(t *testing.T) { genericTest255(t, &io, modp255) })
	t.Run("mula24", func(t *testing.T) { genericTest255(t, &io, mulw255) })
	t.Run("div", func(t *testing.T) { genericTest255(t, &io, divd255) })
}

func BenchmarkFp255(b *testing.B) {
	var x, y, z Element255
	var io test255
	io.F = Fp255
	b.Run("csel", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			io.F.CSel(&x, &y, uint(i))
		}
	})
	b.Run("cswap", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			io.F.CSwap(&x, &y, uint(i))
		}
	})
	b.Run("add", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			io.F.Add(&z, &x, &y)
		}
	})
	b.Run("sub", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			io.F.Sub(&z, &x, &y)
		}
	})
	b.Run("addsub", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			io.F.AddSub(&z, &x)
		}
	})
	b.Run("mul", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			io.F.Mul(&z, &x, &y)
		}
	})
	b.Run("sqr", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			io.F.Sqr(&z, &x)
		}
	})
	b.Run("modp", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			io.F.Modp(&z)
		}
	})
	b.Run("div", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			io.F.Div(&z, &x, &y)
		}
	})
}

// Code autogenerated by go generate; DO NOT EDIT.
