// Code generated by go generate; DO NOT EDIT.

package mceliece348864

func int32MinMax(a, b *int32) {
	ab := *b ^ *a
	c := *b - *a
	c ^= ab & (c ^ *b)
	c >>= 31
	c &= ab
	*a ^= c
	*b ^= c
}

func int32Sort(x []int32) {
	n := int64(len(x))
	if n < 2 {
		return
	}
	top := int64(1)
	for top < n-top {
		top += top
	}
	for p := top; p > 0; p >>= 1 {
		for i := int64(0); i < n-p; i++ {
			if i&p == 0 {
				int32MinMax(&x[i], &x[i+p])
			}
		}
		i := int64(0)
		for q := top; q > p; q >>= 1 {
			for ; i < n-q; i++ {
				if i&p == 0 {
					a := x[i+p]
					for r := q; r > p; r >>= 1 {
						int32MinMax(&a, &x[i+r])
					}
					x[i+p] = a
				}
			}
		}
	}
}

func uint64MinMax(a, b *uint64) {
	c := *b - *a
	c >>= 63
	c = -c
	c &= *a ^ *b
	*a ^= c
	*b ^= c
}

func uint64Sort(x []uint64) {
	n := int64(len(x))
	if n < 2 {
		return
	}
	top := int64(1)
	for top < n-top {
		top += top
	}
	for p := top; p > 0; p >>= 1 {
		for i := int64(0); i < n-p; i++ {
			if i&p == 0 {
				uint64MinMax(&x[i], &x[i+p])
			}
		}
		i := int64(0)
		for q := top; q > p; q >>= 1 {
			for ; i < n-q; i++ {
				if i&p == 0 {
					a := x[i+p]
					for r := q; r > p; r >>= 1 {
						uint64MinMax(&a, &x[i+r])
					}
					x[i+p] = a
				}
			}
		}
	}
}
