// Code generated by command: go run ntt_amd64_src.go -out ntt_amd64.s -stubs ntt_amd64_stubs.go. DO NOT EDIT.

// +build amd64

package internal

//go:noescape
func nttAVX2(p *[256]uint32)

//go:noescape
func invNttAVX2(p *[256]uint32)

//go:noescape
func mulHatAVX2(p *[256]uint32, a *[256]uint32, b *[256]uint32)

//go:noescape
func addAVX2(p *[256]uint32, a *[256]uint32, b *[256]uint32)

//go:noescape
func subAVX2(p *[256]uint32, a *[256]uint32, b *[256]uint32)

//go:noescape
func packLe16AVX2(p *[256]uint32, buf *byte)
