// Code generated by go generate; DO NOT EDIT.

package mceliece6960119

import (
	"bytes"
	"testing"

	"github.com/cloudflare/circl/kem"
)

func TestSchemeRoundTrip(t *testing.T) {
	sch := Scheme()
	seed := bytes.Repeat([]byte{0x11}, sch.SeedSize())
	pk, sk := sch.DeriveKeyPair(seed)
	ct, ss, err := sch.EncapsulateDeterministically(pk, bytes.Repeat([]byte{0x22}, sch.EncapsulationSeedSize()))
	if err != nil {
		t.Fatal(err)
	}
	ss2, err := sch.Decapsulate(sk, ct)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(ss, ss2) {
		t.Fatalf("shared secret mismatch")
	}
}

func TestMarshalRoundTrip(t *testing.T) {
	sch := Scheme()
	pk, sk := sch.DeriveKeyPair(bytes.Repeat([]byte{0x33}, sch.SeedSize()))
	pkb, err := pk.MarshalBinary()
	if err != nil {
		t.Fatal(err)
	}
	skb, err := sk.MarshalBinary()
	if err != nil {
		t.Fatal(err)
	}
	pk2, err := sch.UnmarshalBinaryPublicKey(pkb)
	if err != nil {
		t.Fatal(err)
	}
	sk2, err := sch.UnmarshalBinaryPrivateKey(skb)
	if err != nil {
		t.Fatal(err)
	}
	if !pk.Equal(pk2) || !sk.Equal(sk2) {
		t.Fatalf("key equality failed after marshal/unmarshal")
	}
	if !pk.Equal(sk2.Public().(kem.PublicKey)) {
		t.Fatalf("recovered public key mismatch")
	}
}

// TestDecapsulateBadPaddingNoPanic is a regression test: a correctly sized
// ciphertext whose padding bits are non-zero must not panic through the public
// Scheme.Decapsulate / DecapsulateTo path (a remote peer controls the
// ciphertext). Matching the reference, decapsulation succeeds but returns a
// shared secret that is deterministically mangled by the padding mask, so it
// differs from the value the honest sender derived.
func TestDecapsulateBadPaddingNoPanic(t *testing.T) {
	sch := Scheme()
	pk, sk := sch.DeriveKeyPair(bytes.Repeat([]byte{0x44}, sch.SeedSize()))
	ct, ss, err := sch.EncapsulateDeterministically(pk, bytes.Repeat([]byte{0x55}, sch.EncapsulationSeedSize()))
	if err != nil {
		t.Fatal(err)
	}

	// Flip a padding bit in the last syndrome byte, keeping the length valid.
	badCT := append([]byte(nil), ct...)
	badCT[CiphertextSize-1] |= 0x80

	ss2, err := sch.Decapsulate(sk, badCT)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(ss2) != sch.SharedKeySize() {
		t.Fatalf("unexpected shared secret size %d", len(ss2))
	}
	if bytes.Equal(ss, ss2) {
		t.Fatalf("bad-padding ciphertext yielded the honest shared secret")
	}
}
