// Code generated by go generate; DO NOT EDIT.

// Package mceliece6688128 implements the Classic McEliece mceliece6688128
// Round 4 parameter set. The code is a direct, scalar Go port of the official
// 2022-10-23 reference implementation.
package mceliece6688128

const (
	GFBits = 13
	SysN   = 6688
	SysT   = 128

	CondBytes = (1 << (GFBits - 4)) * (2*GFBits - 1)
	IrrBytes  = SysT * 2

	PKNRows     = SysT * GFBits
	PKNCols     = SysN - PKNRows
	PKRowBytes  = (PKNCols + 7) / 8
	SyndBytes   = (PKNRows + 7) / 8
	PKNRowsMod8 = PKNRows % 8

	GFMask = (1 << GFBits) - 1

	PublicKeySize  = 1044992
	PrivateKeySize = 13932
	CiphertextSize = 208
	SharedKeySize  = 32
	SeedSize       = 32
)

type gf uint16
