// Code generated by go generate; DO NOT EDIT.

package mceliece6688128

func genpolyGen(out *[SysT]gf, f *[SysT]gf) int {
	var mat [SysT + 1][SysT]gf
	mat[0][0] = 1
	for i := 1; i < SysT; i++ {
		mat[0][i] = 0
	}
	for i := 0; i < SysT; i++ {
		mat[1][i] = f[i]
	}
	for j := 2; j <= SysT; j++ {
		gfMulPoly(&mat[j], &mat[j-1], f)
	}

	for j := 0; j < SysT; j++ {
		for k := j + 1; k < SysT; k++ {
			mask := gfIsZero(mat[j][j])
			for c := j; c < SysT+1; c++ {
				mat[c][j] ^= mat[c][k] & mask
			}
		}
		if uint16EqualMask(uint16(mat[j][j]), 0) == 0xffff {
			return -1
		}
		inv := gfInv(mat[j][j])
		for c := j; c < SysT+1; c++ {
			mat[c][j] = gfMul(mat[c][j], inv)
		}
		for k := 0; k < SysT; k++ {
			if k != j {
				t := mat[j][k]
				for c := j; c < SysT+1; c++ {
					mat[c][k] ^= gfMul(mat[c][j], t)
				}
			}
		}
	}
	for i := 0; i < SysT; i++ {
		out[i] = mat[SysT][i]
	}
	return 0
}
