// Code generated by go generate; DO NOT EDIT.

package mceliece6688128

func synd(out *[SysT * 2]gf, f *[SysT + 1]gf, l *[SysN]gf, r []byte) {
	for j := 0; j < 2*SysT; j++ {
		out[j] = 0
	}
	for i := 0; i < SysN; i++ {
		c := gf((r[i/8] >> uint(i%8)) & 1)
		e := eval(f, l[i])
		eInv := gfInv(gfMul(e, e))
		for j := 0; j < 2*SysT; j++ {
			out[j] = gfAdd(out[j], gfMul(eInv, c))
			eInv = gfMul(eInv, l[i])
		}
	}
}
